networks:
    default:
        name: appnetwork
        external: true
services:
    vector-db-cli:
        image: vector-db-cli
        container_name: vector-db-cli
        volumes:
            - ../../secrets:/secrets
            - ../vector-db:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
            CHROMADB_HOST: vector-db
            CHROMADB_PORT: 8000
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: vector-db
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
