name: CI

on:
  push:
    branches:
      - Milestone4  # Triggers when code is pushed to the Milestone4 branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Log basic workflow information
      - run: echo "Comment ${{ github.event.head_commit.message }}"
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.DEPLOYMENT }}'

      # Configure Google Cloud SDK
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Install Docker Client
      - name: Configure Docker Client
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      # Create secrets directory and files
      - name: Create secrets directory
        run: |
          mkdir -p ${{ github.workspace }}/secrets
          chmod 0777 ${{ github.workspace }}/secrets

      - name: Create secrets files
        run: |
          echo '${{ secrets.DEPLOYMENT }}' > ${{ github.workspace }}/src/food_classification/secrets/ac215-smarteat-437821-15c2f229e610.json
          
      # Log repository information
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      # List all files in the repository for debugging
      - name: List files in the repository
        run: |
          ls -R ${{ github.workspace }}

      # Ensure docker-shell.sh exists and has the right permissions
      - name: Verify docker-shell.sh exists
        run: |
          if [ ! -f ${{ github.workspace }}/src/food_classification/docker-shell.sh ]; then
            echo "Error: docker-shell.sh not found!" && exit 1
          fi
          chmod +x ${{ github.workspace }}/src/food_classification/docker-shell.sh

      # Build and run the deployment container
      - name: Build Deployment Container 
        run: |
          cd ${{ github.workspace }}/src/food_classification/
          sh docker-shell.sh
      
      # Uncomment these steps if you need to pull and run tests in the Docker container
      # - name: Pull Docker image
      #   run: docker pull jsunsun/ms4_step1:latest

      # - name: Run tests in Docker container with coverage
      #   run: |
      #     docker run --rm \
      #       -v ${{ github.workspace }}/src:/app/src \
      #       -v ${{ github.workspace }}/tests:/app/tests \
      #       -v ${{ github.workspace }}/coverage:/app/coverage \
      #       jsunsun/ms4_step1:latest pytest --cov=/app/src --cov-report=html:/app/coverage

      # Step 4: Upload coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage  # Path to the coverage report folder
