name: CI

on:
  push:
    branches:
      - Milestone4  # Triggers when code is pushed to the Milestone4 branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Pull the Docker image
      # - name: Pull Docker image
      #   run: docker pull jsunsun/ms4_step1:latest
      - name: Build Docker image for AMD64
        run: |
          docker build --platform linux/amd64 -t jsunsun/ms4_step1_image:latest .
      

      # Step 3: Run tests in the Docker container
      - name: Run tests in Docker container with coverage
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/src:/app/src \
            -v ${{ github.workspace }}/tests:/app/tests \
            -v ${{ github.workspace }}/coverage:/app/coverage \
            jsunsun/ms4_step1:latest pytest --cov=/app/src --cov-report=html:/app/coverage

      # Step 4: Upload coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage  # Path to the coverage report folder
